name: Debug Real Error Demo

on:
  workflow_dispatch:

jobs:
  debug-real-error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Step with real error and verbose output
        run: |
          set -x
          echo "Trying to read a non-existent file..."
          cat /tmp/this-file-does-not-exist.txt
